communication_backend: serial

serial:
  baudrate: 57600
  port: COM4
  timeout: 5 # Seconds

bluetooth:
  mac_address: 74B1AEEB-6720-4DCB-94BC-623775EA3529

# Joystick UUID mapping to number
# TODO This will be updated by the driverstation
joystick_mapping:
  030000005e040000ff02000000007200: 1
