#communication_backend: serial
communication_backend: bluetooth

logging:
  global_level: DEBUG
  driver_station: INFO
  serial_level: INFO
  bluetooth_level: INFO
  bleak_level: INFO

serial:
  baudrate: 115200
  port: COM4
  timeout: 5 # Seconds

bluetooth:
  mac_address: 48:87:2D:14:8D:2E

# Joystick UUID mapping to number
# TODO This will be updated by the driverstation
joystick_mapping:
  030000005e040000ff02000000007200: 1
